version: '2.4'

services:
#  kabal-innstillinger:
#    depends_on:
#      kabal-db:
#        condition: service_healthy
#    build: .
#    ports:
#    - "7070:7070"
#    environment:
#      SPRING_PROFILES_ACTIVE: local
  kabal-db:
    container_name: kabal-db
    image: library/postgres:12
    environment:
      POSTGRES_USER: klage
      POSTGRES_PASSWORD: klage
      POSTGRES_DB: kabal-innstillinger
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U klage -d kabal-innstillinger"
      interval: 3s
      timeout: 5s
      retries: 5
#  postgres: