TENANT_ID: 966ac572-f5b7-4bbe-aa88-c76419c0f851

NORG2_API_V1_URL: https://api-gw-q1.oera.no/norg2/api/v1

EREG_URL: https://api-gw-q1.oera.no/ereg/api

AXSYS_URL: https://api-gw-q1.oera.no/axsys/api/v2
AXSYS_CLUSTER: dev-fss
AXSYS_NAMESPACE: org
AXSYS_APP: axsys

KABAL_OPPGAVESTYRING_ALLE_ENHETER: 7ad08bfe-68d4-4c84-bddd-82d8894fb36e
KABAL_MALTEKSTREDIGERING: 0097d4ff-787d-4180-953a-8d60b7927f32
KABAL_SAKSBEHANDLING: 07add1e7-7195-4c37-828d-fdf23ec6bef1
KABAL_FAGTEKSTREDIGERING: 94d34f17-e325-4ed6-9667-d23041a3f40c
KABAL_OPPGAVESTYRING_EGEN_ENHET: 016fb83f-4e7c-47ec-ae8a-e3efa72a43e7
FORTROLIG: 2980c598-8af7-473f-b7d1-233f785d7001
STRENGT_FORTROLIG: de92036b-c350-471c-9249-753f36acd24d
EGEN_ANSATT: 011af9b0-792d-4d2c-a2eb-9a59fc095002

KABAL_ADMIN: a9f5ef81-4e81-42e8-b368-0273071b64b9

PDL_BASE_URL: https://pdl-api.dev-fss-pub.nais.io/graphql
PDL_SCOPE: dev-fss.pdl.pdl-api
