TENANT_ID: 966ac572-f5b7-4bbe-aa88-c76419c0f851

NORG2_API_V1_URL: https://api-gw-q1.oera.no/norg2/api/v1

EREG_URL: https://api-gw-q1.oera.no/ereg/api

AXSYS_URL: https://api-gw-q1.oera.no/axsys/api/v2
AXSYS_CLUSTER: dev-fss
AXSYS_NAMESPACE: org
AXSYS_APP: axsys

PDL_BASE_URL: https://pdl-api.dev-fss-pub.nais.io/graphql
PDL_SCOPE: dev-fss.pdl.pdl-api
