TENANT_ID: 62366534-1ec3-4962-8869-9b5535279d0b

SETTINGS_CLEANUP_CRON: 0 30 14 * * MON

spring:
  datasource:
    url: jdbc:postgresql://${NAIS_DATABASE_KABAL_INNSTILLINGER_KABAL_INNSTILLINGER_HOST}:${NAIS_DATABASE_KABAL_INNSTILLINGER_KABAL_INNSTILLINGER_PORT}/${NAIS_DATABASE_KABAL_INNSTILLINGER_KABAL_INNSTILLINGER_DATABASE}
    username: ${NAIS_DATABASE_KABAL_INNSTILLINGER_KABAL_INNSTILLINGER_USERNAME}
    password: ${NAIS_DATABASE_KABAL_INNSTILLINGER_KABAL_INNSTILLINGER_PASSWORD}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
