TENANT_ID: 62366534-1ec3-4962-8869-9b5535279d0b

NORG2_API_V1_URL: https://norg2.prod-fss-pub.nais.io/norg2/api/v1

EREG_URL: https://ereg-services.prod-fss-pub.nais.io/ereg/api

PROXY_APP_CLIENT_ID: 981be1fb-1379-465f-bddc-7563197aed84

PDL_BASE_URL: https://pdl-api.prod-fss-pub.nais.io/graphql
PDL_SCOPE: prod-fss.pdl.pdl-api

NOM_BASE_URL: https://nom-api.intern.nav.no/graphql
NOM_SCOPE: prod-gcp.nom.nom-api