SECURITY_TOKEN_SERVICE_REST_URL: http://localhost:8088
SERVICE_USER_USERNAME: igroup
NAIS_CLUSTER_NAME: local
AZURE_APP_WELL_KNOWN_URL: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0/.well-known/openid-configuration
NORG2_API_V1_URL: local
NORG2_APIKEY: 123
AXSYS_APIKEY: 357
nais:
  cluster:
    name: local

NAIS_DATABASE_KABAL_INNSTILLINGER_KABAL_INNSTILLINGER_USERNAME: klage
NAIS_DATABASE_KABAL_INNSTILLINGER_KABAL_INNSTILLINGER_PASSWORD: klage
NAIS_DATABASE_KABAL_INNSTILLINGER_KABAL_INNSTILLINGER_DATABASE: kabal-innstillinger
NAIS_DATABASE_KABAL_INNSTILLINGER_KABAL_INNSTILLINGER_HOST: localhost
NAIS_DATABASE_KABAL_INNSTILLINGER_KABAL_INNSTILLINGER_PORT: 5432

AXSYS_URL: https://axsys.dev.adeo.no/v1

ROLE_KLAGE_OPPGAVESTYRING_ALLE_ENHETER: xxxx
ROLE_KLAGE_MALTEKSTREDIGERING: xxxx
ROLE_KLAGE_SAKSBEHANDLER: 07add1e7-7195-4c37-828d-fdf23ec6bef1
ROLE_KLAGE_FAGANSVARLIG: 94d34f17-e325-4ed6-9667-d23041a3f40c
ROLE_KLAGE_LEDER: 016fb83f-4e7c-47ec-ae8a-e3efa72a43e7
ROLE_KLAGE_FORTROLIG: 2980c598-8af7-473f-b7d1-233f785d7001
ROLE_KLAGE_STRENGT_FORTROLIG: de92036b-c350-471c-9249-753f36acd24d
ROLE_KLAGE_EGEN_ANSATT: 011af9b0-792d-4d2c-a2eb-9a59fc095002

PDL_BASE_URL: local
PDL_APIKEY: 159